_BASE_: ../../vita/mevis/vita_R50_bs8.yaml
MODEL:
  META_ARCHITECTURE: "Genvis"
  WEIGHTS: "checkpoints/genvis_r50_w1_ovis.pth"
  VITA:
    ENC_WINDOW_SIZE: 0
    FREEZE_DETECTOR: True
  GENVIS:
    LEN_CLIP_WINDOW: 15
DATASETS:
  DATASET_RATIO: [1.0, 0.25]
  TRAIN: ("mevis_train",)
  TEST: ("mevis_val",)
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (100000,)
  MAX_ITER: 140000
  CHECKPOINT_PERIOD: 5000
INPUT:
  SAMPLING_FRAME_NUM: 30
  SAMPLING_FRAME_RANGE: 12
  SAMPLING_FRAME_SHUFFLE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 20
