_BASE_: ../../vita/mevis/vita_R50_bs8.yaml
MODEL:
  META_ARCHITECTURE: "Genvis"
  WEIGHTS: "checkpoints/vita_r50_ovis.pth"
  VITA:
    ENC_WINDOW_SIZE: 0
    FREEZE_DETECTOR: True
  GENVIS:
    LEN_CLIP_WINDOW: 1
DATASETS:
  DATASET_RATIO: [1.0, 0.25]
  TRAIN: ("refyt_train",)
  TEST: ("refyt_val",)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (100000,)
  MAX_ITER: 140000
  CHECKPOINT_PERIOD: 5000
INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 6
  SAMPLING_FRAME_SHUFFLE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 10